apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-sc
spec:
  accessModes:
    - ReadWriteMany   # should be same as in persistentVolume
  resources:
    requests:
      storage: 5Gi     # should be same as in persistentVolume
  storageClassName: "demo-storage"  # name of the storage class