version: "3.8"   --> docker-compose file format version
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - abhi:/usr/share/nginx/html
  backend:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      - DB_URL=mongodb://database/abhi (or) DB_URL: mongodb://database/abhi
  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes: 
      - abhi:/data/db
volumes:
  abhi: 