apiVersion: v1 #it is the version of kubernetes object and it varies from resource to resource kubectl api-resources | grep pods
kind: Pod # it is the type of object
metadata: # information about the object
  name: nginx-pod1
  labels: # act like identifiers to the pods
    team: integrations
    app: todo
spec: # actual specifications of the object and attributes vary from object to object
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
      requests:
        memory: "64Mi"   # Requesting 64 megabytes of memory
        cpu: "250m"      # Requesting 250 millicpu (.25 CPU cores)
      limits:
        memory: "128Mi"  # Limiting memory usage to 128 megabytes
        cpu: "500m" 
description: >
    1  exit
    2  minikube start --nodes 2 -p local-cluster --driver=docker
    3  kubectl get all
    4  minikube status -p local-cluster
    5  kubectl config get-context 
    6  kubectl config get-contexts
    7  minikube dashboard --url -p local-cluster
    8  kubectl run nginx-pod --image=nginx
    9  kubectl get pod
    10  kubectl get pods
    11  kubectl api-resources | pods
    12  kubectl api-resources | pod
    13  kubectl api-resources | grep pods
    14  mkdir nginx
    15  cd nginx
    16  vi nginx-pod.yaml
    17  kubectl apply -f nginx-pod.yaml
    18  vi nginx-pod.yaml
    19  kubectl apply -f nginx-pod.yaml
    20  vi nginx-pod.yaml
    21  kubectl apply -f nginx-pod.yaml
    22  kubectl get pods
    23  history
    24  kubectl get pods -l team=integrations
    25  kubectl get pods -l team=integrations,app=todo
    26   kubectl get pod nginx-pod1 -o wide
    27  kubectl get pod nginx-pod1 -o yaml
    28  kubectl describe pod nginx-pod1
    29  kubectl exxec -it nginx-pod1 -- bash
    30  kubectl exec -it nginx-pod1 -- bash
    31  kubectl exec -it nginx-pod1 -c nginx-container -- bash
    32  kubectl port-forward nginx-pod1 8083:80
    33  kubectl logs nginx-pod1
    34  kubectl delete -f nginx-pod.yaml
    35  kubectl get pods
    36  kubectl delete pod nginx-pod 
    37  kubectl get pods
    38  kubectl get po
    39  history