- name: local-cluster   # arrays (starting with "-" means it is an array )
  isActive: true
  createdAt: 2021-09-25 21:11:15
  version: !!str &clusterVersion 1.22.1   # (!!str means the data type is explicitly provided)  (&clusterVersion means anchors i.e, that variable can be used anywhere starting with *)
  access:                  # object (in k8s these are called as dictionary or map)
    ip: 192.168.58.2
    port: 8443
  nodes:
    - name: local-vluster-01
      type: master
      tags: ["local", "master"]
    - name: local-cluster-02
      type: worker
      tags: ["local", "worker"]  
  description: >   # folded block (preserve in a single line though it is written in two lines)
    This is the local cluser created on minikube.
    And the driver I uswed is Docker!
  longDescription: |    # little block (preserves same as written)
     This is the local cluser created on minikube.
     And the driver I uswed is Docker!
- name: dev-cluster   # arrays (starting with "-" means it is an array )
  isActive: true
  createdAt: 2021-09-24 21:11:15
  version: *clusterVersion  # to access the variable * is used
  access:
    ip: 192.168.58.3
    port: 8443
  nodes:
    - name: dev-vluster-01
      type: master
      tags: ["dev", "master"]  # or tags:
                                  #   - dev   the array elements can be indented to parent level also
                                   #  - master
    - name: dev-cluster-02
      type: worker
      tags: ["dev", "worker"]

--- # to separate another yaml code
